spring:
  application:
    name: auth-service

  config.import: optional:configserver:http://localhost:8888

  datasource:
    url: jdbc:mysql://localhost:3306/authdb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: auth_user
    password: Welcome@1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8081

auth:   # 👈 must match JwtProperties prefix
  jwt:
    secret: "0GCc0cRjAlV9K59XOppI61XU6w9p7WE29oa7N7fsmTc="
    expiryMinutes: 60
eureka:
  instance:
    lease-renewal-interval-in-seconds: 30   # heartbeat every 30s
    lease-expiration-duration-in-seconds: 90 # wait 90s before eviction
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

      # expose health/info for monitoring

 

    
  


